/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_beton_hilihase_jfw_Sample2 */

#ifndef _Included_hu_beton_hilihase_jfw_Sample2
#define _Included_hu_beton_hilihase_jfw_Sample2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_beton_hilihase_jfw_Sample2
 * Method:    hilihase_drve
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_hu_beton_hilihase_jfw_Sample2_hilihase_1drve
  (JNIEnv *, jobject, jint, jbyte);

#ifdef __cplusplus
}
#endif
#endif
