/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_beton_hilihase_jfw_NativeInterface */

#ifndef _Included_hu_beton_hilihase_jfw_NativeInterface
#define _Included_hu_beton_hilihase_jfw_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_beton_hilihase_jfw_NativeInterface
 * Method:    hilihase_drve
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_hu_beton_hilihase_jfw_NativeInterface_hilihase_1drve
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     hu_beton_hilihase_jfw_NativeInterface
 * Method:    hilihase_start_HDL_sim
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hu_beton_hilihase_jfw_NativeInterface_hilihase_1start_1HDL_1sim
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
